name: Deploy
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Dependencies
        run: "deno install"

      - name: Compile Executable
        run: "deno task compile"

      - name: Create Artifact
        run: |
          mkdir release
          mkdir artifact
          mkdir artifact/output
          mkdir artifact/backup
          mkdir artifact/queue
          Move-Item -Path .\.env.template -Destination .\artifact\.env
          Move-Item -Path .\translate.exe -Destination .\artifact\translate.exe
          Compress-Archive -Path .\artifact\* -DestinationPath .\release\translate-lrc.zip -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: translate-lrc
          path: release/translate-lrc.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          files: release/translate-lrc.zip
          name: ${{ steps.define-version.outputs.commit }}
          prerelease: false
          tag_name:  ${{ steps.define-version.outputs.commit }}
